version: '3.0'

services:
  web:
    build: ./src
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./src/:/usr/src/app/
      - ./data/:/usr/data/
      - ./weights/:/usr/weights/
    env_file:
      - var.env
    ports:
      - 8002:8000
    restart: always
